AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Cosmos backend

Globals:
  Function:
    Timeout: 3

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
            Identity:
              Header: Authorization
        AddDefaultAuthorizerToCorsPreflight: false

      Cors:
        AllowMethods: "'GET,POST,PATCH,OPTIONS'"
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"

  CosmosBackendTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TableName: !Sub "${AWS::StackName}-backend-table"

  # <--- Cognito ---
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-user-pool"
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: web-client
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/getHealth.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetHealth:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /health
            Method: get
            Auth:
              Authorizer: NONE
      Environment:
        Variables:
          TABLE_NAME: !Ref CosmosBackendTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true

  GetMeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/auth/getMe.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        GetMe:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /me
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref CosmosBackendTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true

  PostBrandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/brands/postBrand.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CosmosBackendTable
      Events:
        PostBrand:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /brands
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref CosmosBackendTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true

  GetBrandsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/brands/getBrands.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CosmosBackendTable
      Events:
        GetBrands:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /brands
            Method: get
      Environment:
        Variables:
          TABLE_NAME: !Ref CosmosBackendTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
  PostGenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/brands/postGenerate.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CosmosBackendTable
      Events:
        PostGenerateGlobal:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /brands/{brandId}/generate
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref CosmosBackendTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true

Outputs:
  ApiBaseUrl:
    Description: API base URL for Prod stage
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool
  CognitoUserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref CognitoUserPoolClient
