import { GetCommand, PutCommand, QueryCommand, UpdateCommand } from "@aws-sdk/lib-dynamodb";
import { Brand, BrandSummary, Post, PostMetadata } from "../types/domain";
import { getDocClient, getTableName } from "../clients/dynamo";
import { QueryCommand as DdbQueryCommand } from "@aws-sdk/lib-dynamodb";

export class BrandsRepository {
  private tableName = getTableName();
  private doc = getDocClient();

  async getById(brandId: string): Promise<Brand | null> {
    const res = await this.doc.send(
      new GetCommand({
        TableName: this.tableName,
        Key: { PK: `BRAND#${brandId}`, SK: "BRAND" },
      })
    );
    return (res.Item as Brand) || null;
  }

  async listByUser(userId: string, limit = 50): Promise<BrandSummary[]> {
    const res = await this.doc.send(
      new QueryCommand({
        TableName: this.tableName,
        KeyConditionExpression: "PK = :pk AND begins_with(SK, :prefix)",
        ExpressionAttributeValues: { ":pk": `USER#${userId}`, ":prefix": "BRAND#" },
        ScanIndexForward: false,
        Limit: limit,
      })
    );
    return (res.Items || []).map((it) => ({
      brandId: it.brandId,
      name: it.name,
      createdAt: it.createdAt,
    }));
  }

  async create(userId: string, name: string): Promise<Brand> {
    const now = new Date().toISOString();
    const brandId = Math.random().toString(36).slice(2, 10);
    const brand: Brand = { brandId, userId, name, createdAt: now, updatedAt: now };
    await this.doc.send(
      new PutCommand({
        TableName: this.tableName,
        Item: {
          PK: `BRAND#${brandId}`,
          SK: "BRAND",
          entityType: "BRAND",
          ...brand,
        },
        ConditionExpression: "attribute_not_exists(PK) AND attribute_not_exists(SK)",
      })
    );
    await this.doc.send(
      new PutCommand({
        TableName: this.tableName,
        Item: {
          PK: `USER#${userId}`,
          SK: `BRAND#${now}#${brandId}`,
          entityType: "USER_BRAND",
          brandId,
          userId,
          name,
          createdAt: now,
        },
        ConditionExpression: "attribute_not_exists(PK) AND attribute_not_exists(SK)",
      })
    );
    return brand;
  }

  async updateName(brand: Brand, newName: string): Promise<Brand> {
    const now = new Date().toISOString();
    const updated: Brand = { ...brand, name: newName, updatedAt: now };

    // Update the brand item
    await this.doc.send(
      new UpdateCommand({
        TableName: this.tableName,
        Key: { PK: `BRAND#${brand.brandId}`, SK: "BRAND" },
        UpdateExpression: "SET #n = :n, updatedAt = :u",
        ExpressionAttributeNames: { "#n": "name" },
        ExpressionAttributeValues: { ":n": newName, ":u": now },
      })
    );

    // Update the user pointer item so list results reflect the new name
    await this.doc.send(
      new UpdateCommand({
        TableName: this.tableName,
        Key: { PK: `USER#${brand.userId}`, SK: `BRAND#${brand.createdAt}#${brand.brandId}` },
        UpdateExpression: "SET #n = :n",
        ExpressionAttributeNames: { "#n": "name" },
        ExpressionAttributeValues: { ":n": newName },
      })
    );

    return updated;
  }

  async listPosts(brandId: string, limit = 50): Promise<Post[]> {
    const res = await this.doc.send(
      new DdbQueryCommand({
        TableName: this.tableName,
        KeyConditionExpression: "PK = :pk AND begins_with(SK, :prefix)",
        ExpressionAttributeValues: { ":pk": `BRAND#${brandId}`, ":prefix": "POST#" },
        ScanIndexForward: false,
        Limit: limit,
      })
    );
    return (res.Items || []).map((it) => ({
      postId: (it as any).postId as string,
      userId: (it as any).userId as string,
      brandId: brandId,
      instruction: (it as any).instruction as string,
      title: (it as any).title as string,
      content: (it as any).content as string,
      excerpt: (it as any).excerpt as string | undefined,
      thumbnailUrl: (it as any).thumbnailUrl as string | undefined,
      hashtags: (it as any).hashtags as string[] | undefined,
      status: ((it as any).status as any) ?? "draft",
      metadata: (it as any).metadata as PostMetadata || {},
      createdAt: (it as any).createdAt as string,
      updatedAt: (it as any).updatedAt as string,
    }));
  }

  async createPost(
    userId: string,
    brandId: string,
    instruction: string
  ): Promise<Post> {
    const now = new Date().toISOString();
    const postId = Math.random().toString(36).slice(2, 10);
    
    // Initially create post with "generating" status
    const post: Post = {
      postId,
      userId,
      brandId,
      instruction,
      title: "Generating content...",
      content: "Content is being generated by AI...",
      excerpt: "AI is creating optimized content for your post",
      thumbnailUrl: undefined,
      hashtags: [],
      status: "generating",
      metadata: {
        generatedBy: "llm",
        model: "hardcoded-v1",
        processingTime: 0,
        generationStarted: now,
      },
      createdAt: now,
      updatedAt: now,
    };

    await this.doc.send(
      new PutCommand({
        TableName: this.tableName,
        Item: {
          PK: `BRAND#${brandId}`,
          SK: `POST#${now}#${postId}`,
          entityType: "POST",
          ...post,
        },
        ConditionExpression: "attribute_not_exists(PK) AND attribute_not_exists(SK)",
      })
    );

    return post;
  }

  async getPostById(brandId: string, postId: string): Promise<Post | null> {
    const res = await this.doc.send(
      new DdbQueryCommand({
        TableName: this.tableName,
        KeyConditionExpression: "PK = :pk AND begins_with(SK, :prefix)",
        ExpressionAttributeValues: { 
          ":pk": `BRAND#${brandId}`, 
          ":prefix": "POST#"
        },
        FilterExpression: "postId = :postId",
        ExpressionAttributeValues: {
          ":pk": `BRAND#${brandId}`,
          ":prefix": "POST#",
          ":postId": postId,
        },
      })
    );

    const item = res.Items?.[0];
    if (!item) return null;

    return {
      postId: (item as any).postId as string,
      userId: (item as any).userId as string,
      brandId: brandId,
      instruction: (item as any).instruction as string,
      title: (item as any).title as string,
      content: (item as any).content as string,
      excerpt: (item as any).excerpt as string | undefined,
      thumbnailUrl: (item as any).thumbnailUrl as string | undefined,
      hashtags: (item as any).hashtags as string[] | undefined,
      status: ((item as any).status as any) ?? "draft",
      metadata: (item as any).metadata as PostMetadata || {},
      createdAt: (item as any).createdAt as string,
      updatedAt: (item as any).updatedAt as string,
    };
  }

  async completePostGeneration(brandId: string, postId: string, instruction: string) {
    const generatedContent = this.generateContentForPost(instruction);
    const now = new Date().toISOString();

    // Find the post by querying and filtering
    const res = await this.doc.send(
      new DdbQueryCommand({
        TableName: this.tableName,
        KeyConditionExpression: "PK = :pk AND begins_with(SK, :prefix)",
        ExpressionAttributeValues: { 
          ":pk": `BRAND#${brandId}`, 
          ":prefix": "POST#"
        },
        FilterExpression: "postId = :postId",
        ExpressionAttributeValues: {
          ":pk": `BRAND#${brandId}`,
          ":prefix": "POST#",
          ":postId": postId,
        },
      })
    );

    const item = res.Items?.[0];
    if (!item) {
      console.error(`Post ${postId} not found for completion`);
      return;
    }

    // Update the post with generated content
    await this.doc.send(
      new UpdateCommand({
        TableName: this.tableName,
        Key: { PK: item.PK, SK: item.SK },
        UpdateExpression: "SET title = :title, content = :content, excerpt = :excerpt, thumbnailUrl = :thumbnailUrl, hashtags = :hashtags, #status = :status, updatedAt = :updatedAt, metadata = :metadata",
        ExpressionAttributeNames: {
          "#status": "status"
        },
        ExpressionAttributeValues: {
          ":title": generatedContent.title,
          ":content": generatedContent.content,
          ":excerpt": generatedContent.excerpt,
          ":thumbnailUrl": generatedContent.thumbnailUrl,
          ":hashtags": generatedContent.hashtags,
          ":status": "generated",
          ":updatedAt": now,
          ":metadata": {
            generatedBy: "llm",
            model: "hardcoded-v1",
            processingTime: 15000,
            generationCompleted: now,
          },
        },
      })
    );

    console.log(`Post ${postId} generation completed`);
  }

  private generateContentForPost(instruction: string) {
    // Simple content generation based on instruction
    return {
      title: instruction,
      content: `${instruction}\n\nThis content has been optimized for maximum engagement and reach across social media platforms.`,
      excerpt: `Engaging content: ${instruction}`,
      thumbnailUrl: `https://via.placeholder.com/800x600/4F46E5/FFFFFF?text=${encodeURIComponent("Generated Content")}`,
      hashtags: ["#Content", "#Social", "#Engagement"],
    };
  }
}


